Models/Profile.cs
using Microsoft.AspNetCore.Http;
using Shiftin.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ShiftIn.Models
{
    /// <summary>
    /// Profile ACTS as a publically exposed extension of the ApplicationUser class
    /// Profile Holds data that should be publically accessible by other users
    /// </summary>
    public class Profile
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Username { get; set; }
        public string Picture { get; set; }
        [Required]
        public string Location { get; set; }
        //Houses the interests of a user such as MOPAR or JDM
        public ICollection<Interest> Interests { get; set; }
        //Houses the cars owned by the users
        public ICollection<Car> Cars { get; set; }
        //Houses the events that the user has rsvped for
        public ICollection<Event> Meets { get; set; }
        //Identifying relationship to where one profile has one user
        public ApplicationUser User { get; set; }
        //Utilized for profile picture implementation, not publically exposed
        [NotMapped]
        public IFormFile Upload { get; set; }

    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShiftIn.Models;
using Shiftin.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Shiftin.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        public CarsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            //for io
            _environment = environment;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            if (profileid != null)
            {
                var profile = await _context.Profiles.Include(pr => pr.Cars).ThenInclude(c => c.CarImages).FirstOrDefaultAsync(pid => pid.Id.Equals(profileid));
                Profile userprofile = (Profile)profile;
                return View(userprofile.Cars);
            }
            else
            {
                //Check if user has profile
                var profile = await _context.Profiles.Include(pr => pr.Interests).Include(pr => pr.Cars).ThenInclude(c => c.CarImages).FirstOrDefaultAsync(p => p.User.Id.Equals(userId));
                if (profile == null)
                {
                    ViewBag.MSG("You need to make a profile first");
                    return View("Error");
                }
                else
                {
                    //Return profile view
                    Profile userprofile = (Profile)profile;
                    HttpContext.Session.SetInt32("ProfileId", userprofile.Id);
                    return View(userprofile.Cars);
                }
            }

        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            if (profileid != null)
            {
                var model = new Car();
                model.CarImages.Add(new CarImage());
                return View(model);
            }
            else
            {
                return RedirectToAction("Profiles", "Create");
            }
        }

        /**
         * Used to add multple images when creating a car
         * 
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCarImage([Bind("Id,Name,Year,Make,Model,Description,ProfileId,CarImages")] Car car)
        {
            
            car.CarImages.Add(new CarImage());
            return PartialView("CarImages", car);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveCarImage([Bind("Id,Name,Year,Make,Model,Description,ProfileId,CarImages")] Car car,int carimage)
        {
            var existingParent = _context.Car
               .Where(p => p.Id == car.Id)
               .Include(p => p.CarImages)
               .SingleOrDefault();

            if (existingParent != null)
            {
                // Update parent
                _context.Entry(existingParent).CurrentValues.SetValues(car);
                var existingchild = existingParent.CarImages.First(Ci => Ci.Id == carimage);
                // Delete children
                if (existingchild != null)
                {
                    existingParent.CarImages.Remove(existingchild);
                    _context.CarImage.Remove(existingchild);
                }
                _context.SaveChanges();
            }
            return PartialView("CarImages", existingParent);
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Make,Year,Model,Description,CarImages")] Car car)
        {
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            Profile Profile = (Profile)await _context.Profiles.Include(prof=>prof.Cars).FirstOrDefaultAsync(pid => pid.Id == profileid);
            if (ModelState.IsValid)
            {
                if (car.CarImages.Count > 0)
                {
                    foreach (CarImage carImage in car.CarImages)
                    {
                        if (carImage.Upload != null)
                        {
                            try
                            {
                                /////////////////////GET UPLOADED FILE////////////////////////////
                                string storagepathforuser = "wwwroot/CarImages/" + profileid.ToString() + "/";
                                // Determine whether the directory exists.
                                if (!Directory.Exists(storagepathforuser))
                                {                                    // Try to create the directory.
                                    DirectoryInfo di = Directory.CreateDirectory(storagepathforuser);
                                }
                                var file = Path.Combine(_environment.ContentRootPath, storagepathforuser, carImage.Upload.FileName);
                                using (var fileStream = new FileStream(file, FileMode.Create))
                                {
                                    await carImage.Upload.CopyToAsync(fileStream);
                                }
                                //SET DIRECTORY                            
                                carImage.Path = "/CarImages/" + profileid.ToString() + "/" + carImage.Upload.FileName;
                            }
                            catch (Exception e)
                            {
                                ViewBag.MSG("There was an error in the file upload :(");
                                return View("Error");
                            }
                        }
                    }
                }
                if (Profile.Cars == null)
                {
                    Profile.Cars = new List<Car>();
                }
                Profile.Cars.Add(car);

                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Profiles");
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var car = await _context.Car.Include(c=>c.CarImages).FirstOrDefaultAsync(c=>c.Id == id);
            if (car == null)
            {
                return NotFound();
            }
            else
            {
                if(car.ProfileId == HttpContext.Session.GetInt32("ProfileId"))
                {
                    return View(car);
                }
                else
                {
                    ViewBag.MSG("You do not own this one ;)");
                    return View("Error");
                }
            }
           
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Year,Make,Model,Description,ProfileId,CarImages")] Car car)
        {
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            if (id != car.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {

                    if (car.ProfileId != profileid)
                    {
                        return View("Error");
                    }
                    var existingParent = _context.Car.Where(p => p.Id == car.Id).Include(p => p.CarImages).SingleOrDefault();

                    if (existingParent != null)
                    {
                        // Update parent
                        _context.Entry(existingParent).CurrentValues.SetValues(car);

                        // Update and Insert children
                        foreach (var childModel in car.CarImages)
                        {
                            var existingChild = existingParent.CarImages
                                .Where(c => c.Id == childModel.Id)
                                .SingleOrDefault();

                            if (existingChild != null)
                            {
                                if (childModel.Upload != null)
                                {
                                    //exists
                                    /////////////////////GET UPLOADED FILE////////////////////////////
                                    string storagepathforuser = "wwwroot/CarImages/" + profileid.ToString() + "/";

Controllers/InterestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShiftIn.Models;
using Shiftin.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Shiftin.Controllers
{
    [Authorize]
    public class InterestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InterestsController(ApplicationDbContext context)
        {
            
            _context = context;
        }

        // GET: Interests
        public async Task<IActionResult> Index()
        {
            var profile = await _context.Profiles.Include(p => p.Interests).FirstOrDefaultAsync(prof => prof.Id == HttpContext.Session.GetInt32("ProfileId"));
            Profile prof = (Profile)profile;
            return View(prof.Interests);
        }

        // GET: Interests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interest == null)
            {
                return NotFound();
            }

            return View(interest);
        }

        // GET: Interests/Create
        public IActionResult Create()
        {
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            if (profileid != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Profiles", "Create");
            }
            
        }

        // POST: Interests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Interest interest)
        {
            var profileid = HttpContext.Session.GetInt32("ProfileId");
            Profile Profile =(Profile) await _context.Profiles.Include(prof=>prof.Interests).FirstOrDefaultAsync(pid => pid.Id == profileid);
            if (ModelState.IsValid)
            {
                if(Profile.Interests == null)
                {
                    Profile.Interests = new List<Interest>();
                }
                Profile.Interests.Add(interest);
                              
                _context.Update(Profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(interest);
        }

        // GET: Interests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest.FindAsync(id);
            if (interest == null)
            {
                return NotFound();
            }
            return View(interest);
        }

        // POST: Interests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Interest interest)
        {
            if (id != interest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterestExists(interest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(interest);
        }

        // GET: Interests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interest == null)
            {
                return NotFound();
            }

            return View(interest);
        }

        // POST: Interests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var interest = await _context.Interest.FindAsync(id);
            _context.Interest.Remove(interest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InterestExists(int id)
        {
            return _context.Interest.Any(e => e.Id == id);
        }
    }
}

Views/Profiles/Create.cshtml
@model ShiftIn.Models.Profile

@{
    ViewData["Title"] = "Create";
}

<h1>Create Your Profile</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" placeholder="Your identity on the site" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label">Upload a picture of yourself or your car</label>
                <input asp-for="Upload" accept="image/*" type="file" multiple>
                <span asp-validation-for="Upload" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label">City your located</label>
                <input placeholder="Los Angeles,CA" asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Profiles/Delete.cshtml
@model ShiftIn.Models.Profile

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Profile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Profiles/Details.cshtml
@model ShiftIn.Models.Profile

@{
    ViewData["Title"] = "Details";
}

<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto">
        <div class="bg-white shadow rounded overflow-hidden" style="padding-top:4px;">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3"><img src="@Html.DisplayFor(model=>model.Picture)" alt="..." width="190" class="rounded mb-2 img-thumbnail"></div>
                    <div class="media-body mb-5 text-black">
                        <h4 class="mt-0 mb-0"> @Html.DisplayFor(model => model.Username)</h4>
                        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>@Html.DisplayFor(model => model.Location)</p>
                    </div>
                </div>
            </div>

            <div class="px-2 py-2">
                <h5 class="mb-0">Interests</h5>
                <div class="p-2 rounded shadow-sm bg-light">
                    @if (Model.Interests.Count != 0)
                    {
                        @foreach (var interest in Model.Interests)
                        {
                            <p class="font-weight-bold mb-0"> @interest.Name </p>
                            <p class="font-italic mb-0"> @interest.Description </p>
                        }
                    }
                </div>
            </div>
            <div class="py-2 px-2">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Cars</h5>
                </div>

                @if (Model.Cars.Count != 0)
                {
                    @foreach (var Car in Model.Cars)
                    {
                        <p class="font-weight-bold mb-0">@(Car.Year + " " + Car.Make + " " + Car.Model)</p>
                        <div class="profile mr-3">
                            @if (Car.CarImages != null)
                            {
                                @foreach (var image in Car.CarImages)
                                {
                                    <img src="@(image.Path)" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                }
                            }
                        </div>
                    }
                }
                
            </div>
        </div>
    </div>
</div>

Views/Profiles/Edit.cshtml
@model ShiftIn.Models.Profile

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit your Profile</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="profile mr-3">
                <img src="@Html.DisplayFor(model=>model.Picture)" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                </div>
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Upload a picture of yourself or your car</label>
                    <input asp-for="Upload" accept="image/*" type="file" multiple>
                    <input asp-for="Picture" hidden="hidden" />
                    <span asp-validation-for="Upload" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Profiles/Index.cshtml
@model ShiftIn.Models.Profile

@{
    ViewData["Title"] = "Your Profile";
}
<div class="card shadow py-2 px-2">
    <div class="row">
        <div class="col">
            <div class="p-3 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3"><img src="@Html.DisplayFor(model=>model.Picture)" alt="..." width="230" class="rounded mb-2 img-thumbnail"><a asp-action="Edit" asp-controller="Profiles" class="btn btn-outline-dark btn-sm btn-block">Edit profile</a></div>
                    <div class="media-body mb-5 text-black">
                        <h4 class="mt-0 mb-0"> @Html.DisplayFor(model => model.Username)</h4>
                        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>@Html.DisplayFor(model => model.Location)</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">            
            <div class="p-2 m-1 shadow-sm">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Interests</h5>
                    <a class="card-link" asp-action="Index" asp-controller="Interests">Edit</a>
                </div>
                <div class="p-2 m-2 rounded">
                    @if (Model.Interests.Count != 0)
                    {
                        @foreach (var interest in Model.Interests)
                        {
                            <p class="font-weight-bold mb-0"> @interest.Name </p>
                            <p class="font-italic mb-0"> @interest.Description </p>
                        }
                    }
                    else
                    {
                        <p class="font-italic mb-0">Try adding some interests to improve your profile.</p>
                    }
                </div>
                <a class="btn btn-success btn-sm" asp-controller="Interests" asp-action="Create">Add</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="py-2 px-2 rounded">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Cars</h5>
                    <a class="btn btn-sm" asp-action="Index" asp-controller="Cars">Edit</a>
                </div>
                @if (Model.Cars.Count != 0)
                {

                    @foreach (var Car in Model.Cars)
                    {
                        <div class="m-2 p-2 shadow-sm text-center">
                            <p class="font-weight-bold mb-0">@(Car.Year + " " + Car.Make + " " + Car.Model)</p>
                            <p class="font-italic mb-0"> @(Car.Description) </p>
                            <div class="profile mr-3">
                                @if (Car.CarImages != null)
                                {
                                    @foreach (var image in Car.CarImages)
                                    {
                                        <img src="@(image.Path)" alt="..." class="mb-2 card-img-top">
                                    }
                                }
                            </div>
                        </div>
                    }

                }
                else
                {
                    <p class="font-italic mb-0">Try adding some cars to improve your profile.</p>
                }
                <a class="btn btn-dark btn-sm" asp-controller="Cars" asp-action="Create">Add</a>
                <div class="row">
                    <!--Show users cars-->
                    <div class="col-lg-6 mb-2 pr-lg-1"><img src="" alt="" class="img-fluid rounded -sm"></div>
                </div>
            </div>
        </div>
    </div>
</div>